### PR TITLE
Fix server hang when attempting to read more bytes than a packet has left 

### PR DESCRIPTION
**Pull request by yobson1**
Also updated the Windows SSL build and fixed the IsValid function
Not really sure what was going on with the CanRead function but the simple replacement seems to work much better

### CODE REVIEW

**Comment by Bromvlieg** [comment]
I'm not gonna lie, the code I wrote back then ain't pretty.

The `CanRead` name is pretty misleading as it's used to `Read till a specific sequence`.
Your `solution` to the problem is removing the entire functionality efficiently breaking all backwards compatibility along with the ability to be able to read data until it reaches an `\r\n\r\n` for the [Webserver example](https://github.com/Bromvlieg/gm_bromsock/blob/master/Lua_examples/httphost.lua#L89)

I definitly agree that the code should be removed and placed elsewhere. I'm more than happy to merge your pull request if you make sure that you do not break existing lua scripts. [here](https://github.com/Bromvlieg/gm_bromsock/blob/af81118282149719bd8a25923f897af1ff04b21b/Source/gm_bromsock/LuaWrappers/BromSock.cpp#L421), [here](https://github.com/Bromvlieg/gm_bromsock/blob/af81118282149719bd8a25923f897af1ff04b21b/Source/gm_bromsock/LuaWrappers/BromSock.cpp#L336), [here](https://github.com/Bromvlieg/gm_bromsock/blob/af81118282149719bd8a25923f897af1ff04b21b/Source/gm_bromsock/Objects/SockWrapper.cpp#L103) and [here](https://github.com/Bromvlieg/gm_bromsock/blob/af81118282149719bd8a25923f897af1ff04b21b/Source/gm_bromsock/Objects/SockWrapper.cpp#L116)

Always makes my day seeing you guys continue on it, looking forward being able to merge it!

**Review by Bromvlieg — CHANGES_REQUESTED** [review]
Needed to type my comment in the review rather than just comment on it.

**Comment by Bromvlieg** [comment]
@yobson1 Any status on this? Or should I close the request?

**Comment by yobson1** [comment]
Yeah, sorry. It can be closed, I ended up using this https://github.com/glua/gm_glsock for my project instead. Thanks.

**Pull request closed without merging**
